# Site settings
title: Evan Wu's Writings
author:
  name: Evan Wu
  email: wue148070@gmail.com
description: "A portfolio of my writings"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
